## Client ##
type: Client

# Enable Personalized Training
personalization:
  enable: True
  freeze_backbone: True
  adaptive_layer_freezing: True

# Adaptive Learning Rate per Client
adaptive_lr:
  enable: True
  base_lr: 0.01
  min_lr: 0.001
  max_lr: 0.05
  strategy: "gradient_variance"

# Client Trust Score Filtering
trust_filtering:
  enable: True  # Ensure this section is included
  trust_threshold: 0.5
