## Clientt ##
type: RCLClient

ce_loss:
  weight: 1

prox_loss:
  weight: 0

rcl_loss:
  loss_type: supervised
  topk_pos: 1
  topk_neg: 2
  temp: 0.05
  pairs:
    - name: scl
      pos: nn
      neg: nn
      weight: 1
      loss_type: supervised
    - name: penalty
      pos: "nn"
      neg: "nn"
      weight: 1
      loss_type: unsupervised
      neg_sample_type: intra_class_thresholding
      threshold: 0.7
  weight: 1
  branch_level: [0,1,2,3,4]
  feature_relu: False

feature_align_loss:
  weight: 0
  align_type: cosine

# Trust filtering configuration
trust_filtering:
  enable: true
  trust_threshold: 0.5

# Personalization configuration
personalization:
  enable: true
  freeze_backbone: false
  adaptive_layer_freezing: true
  freeze_ratio: 0.5

# Adaptive learning rate configuration
adaptive_lr:
  enable: true
  beta: 0.1  # Factor for adaptive learning rate calculation
  min_lr: 0.001  # Minimum learning rate
  max_lr: 0.1  # Maximum learning rate

# Cyclical learning rate
cyclical_lr: true
base_lr: 0.001
max_lr: 0.1
step_size: 10

# Knowledge distillation
distillation: true
distillation_temp: 3.0
distillation_weight: 0.7

# Multi-level contrastive learning
multi_level_rcl: true
layer_weights: [0.2, 0.2, 0.2, 0.2, 0.2]

# Relaxed contrastive loss parameters
temperature: 0.05
beta: 1.0
lambda_threshold: 0.7

# EWC regularization
ewc_enabled: true
ewc_lambda: 0.4
ewc_importance: 5000
