## Trainer ##
type: Trainer
num_clients: 100
participation_rate: 0.05  # 5% of clients participate per round

# Learning Rate Configuration
local_lr: 0.1
local_lr_decay: 0.998
global_lr: 1.0
global_rounds: 500
local_epochs: 5

# Adaptive Learning Rate
adaptive_lr:
  enable: True
  base_lr: 0.01
  min_lr: 0.001
  max_lr: 0.05
  strategy: "gradient_variance"

# Personalization Settings
personalization:
  enable: True
  freeze_backbone: True
  adaptive_layer_freezing: True

# Trust-Based Client Filtering
trust_filtering:
  enable: True

# Move `trust_threshold` here!
trust_threshold: 0.5  # Minimum trust score to include a client in aggregation
