# configs/model/personalized_resnet18.yaml
type: "PersonalizedResNet18"
name: "PersonalizedResNet18"
num_classes: 10
pretrained: False
l2_norm: True
use_bn_layer: True
last_feature_dim: 512
personalization_layers: 2

projection_head:
  enable: true
  hidden_dim: 512
  output_dim: 128
  use_bn: true

multi_level_features:
  enable: true
  layers: ["layer1", "layer2", "layer3", "layer4"]

adaptive_freezing:
  enable: true
  initial_freeze_ratio: 0.5
  decay_rate: 0.05

