type: "PersonalizedResNet18"  # Changed from "build_personalized_resnet18"
name: "PersonalizedResNet18"
num_classes: 10
pretrained: False
l2_norm: False
use_bn_layer: False
last_feature_dim: 512
personalization_layers: 1
