type: "PersonalizedResNet18"
name: "PersonalizedResNet18"
num_classes: 10
pretrained: False
l2_norm: True
use_bn_layer: True
last_feature_dim: 512
personalization_layers: 2

projection_head:
  enable: true
  hidden_dim: 512
  output_dim: 128
  use_bn: true
