
# #################### Default Setup ####################
# wandb: False
# seed: 0
# enable_benchmark: True
# use_amp: True
# multiprocessing: False
# main_gpu: '0'
# num_workers: 0
# pin_memory: True
# refactoring: True
# verbose: False
# # method_name: FedAvg
# remark: ""

# checkpoint_path: './checkpoints'
# exp_name: base
# output_model_path: 'res18.pt'
# save_freq: 1000
# batch_size: 50
# save_test: False 

# ## Resume
# load_model_path: False      # ====> may be like ./checkpoints/CIFAR100/iid/iid_base/res18.pt. use command line +load_model_path=(path)
# wandb_resume_id: False


# ###### wandb && logging ######
# project: "FedRCL"
# log_dir: './checkpoints' 


# #################### Data Split ####################
# split:
#   mode: 'dirichlet'
#   alpha: 0.3
#   class_per_client: 0 # only for skew mode
#   unbalanced: False
#   overlap_ratio: 0.0
#   create_client_dataset: False

# #################### Optimizer ####################
# optimizer:
#   name: sgd
#   momentum: 0.0
#   wd: 1e-3


# #################### Eval ###################
# eval:
#   freq: 1
#   batch_size: 128

# analysis: False

# defaults:
#   - _self_
#   - trainer: base
#   - client: base
#   - evaler: base
#   - dataset: cifar100
#   - server: base
#   - model: resnet18
#   # - override hydra/job_logging: colorlog_custom
#   # - override hydra/hydra_logging: colorlog

#################### Default Setup ####################
wandb: False
seed: 0
enable_benchmark: True
use_amp: True
multiprocessing: False
main_gpu: '0'
num_workers: 0
pin_memory: True
refactoring: True
verbose: False
remark: ""

checkpoint_path: './checkpoints'
exp_name: base
output_model_path: 'res18.pt'
save_freq: 1000
batch_size: 50
save_test: False

## Resume
load_model_path: False      # Example: ./checkpoints/CIFAR100/iid/iid_base/res18.pt
wandb_resume_id: False

###### wandb && logging ######
project: "FedRCL-Personalized"
log_dir: './checkpoints'

#################### Data Split ####################
split:
  mode: 'dirichlet'
  alpha: 0.3
  class_per_client: 0 # Only for skew mode
  unbalanced: False
  overlap_ratio: 0.0
  create_client_dataset: False

#################### Optimizer ####################
optimizer:
  name: sgd
  momentum: 0.9
  wd: 1e-3

#################### Adaptive Learning Rate ####################
adaptive_lr:
  enable: True  # Set to False to disable adaptive learning rate
  base_lr: 0.01
  min_lr: 0.001
  max_lr: 0.05
  strategy: "gradient_variance"  # Options: "gradient_variance", "meta_learning", "reinforcement_learning"

#################### Personalization ####################
personalization:
  enable: True  # Set to False to disable personalized models
  freeze_backbone: True  # Only fine-tune client-specific layers
  trust_threshold: 0.5  # Minimum trust score to include client updates
  adaptive_layer_freezing: True  # Enable adaptive freezing of model layers

#################### Eval ####################
eval:
  freq: 1
  batch_size: 128

analysis: False
defaults:
  - _self_
  - trainer: base
  - client: base  # Ensure client config is loaded!
  - evaler: base
  - dataset: cifar100
  - server: base
  - model: personalized_resnet18

