# fedrcl_p.yaml
#################### Default Setup ####################
wandb: False
seed: 0
enable_benchmark: True
use_amp: True
multiprocessing: False
main_gpu: '0'
num_workers: 2
pin_memory: True
refactoring: True
verbose: False
remark: "personalized"

checkpoint_path: './checkpoints'
exp_name: "FedRCL-P"
output_model_path: 'fedrcl_p_model.pt'
save_freq: 10
batch_size: 64
save_test: True

## Resume options
load_model_path: False
wandb_resume_id: False

###### wandb && logging ######
project: "FedRCL-Personalized"
log_dir: './checkpoints'

#################### Data Split ####################
split:
  mode: 'dirichlet'  # Options: 'iid', 'dirichlet', 'skew'
  alpha: 0.3  # Lower alpha = more non-IID
  class_per_client: 0  # Only for skew mode
  unbalanced: False
  overlap_ratio: 0.0
  create_client_dataset: False
  share_balanced_subset: true  # Share balanced data across clients
  samples_per_class: 50  # Number of samples per class in balanced subset
  samples_per_client: 20  # Number of samples to share with each client

#################### Optimizer ####################
optimizer:
  name: sgd
  momentum: 0.9
  wd: 1e-4

#################### Eval ####################
eval:
  freq: 5  # Evaluate every 5 rounds
  batch_size: 128

#################### Trust-Based Client Filtering ####################
trust_filtering:
  enable: true
  threshold: 0.5
  min_trusted_clients: 1
  soft_filtering: true  # Use soft weighting instead of hard filtering

#################### Personalization Settings ####################
personalization:
  enable: true
  layers: 2  # Number of personalized layers
  knowledge_distillation: true
  kd_temperature: 3.0

#################### Adaptive Learning Rate ####################
adaptive_lr:
  enable: true
  base_lr: 0.001
  max_lr: 0.1

#################### Multi-Level Contrastive Learning ####################
contrastive:
  multi_level: true
  layer_weights: [0.1, 0.2, 0.2, 0.2, 0.3]

#################### Analysis Settings ####################
analysis: True  # Enable analysis to track personalization benefits

#################### Default Configurations ####################
defaults:
  - _self_
  - trainer: personalized
  - client: personalized
  - evaler: base
  - dataset: cifar100
  - server: personalized
  - model: personalized_resnet18
