#################### Default Setup ####################
wandb: False
seed: 0
enable_benchmark: True
use_amp: True
multiprocessing: False
main_gpu: '0'
num_workers: 2
pin_memory: True
refactoring: True
verbose: False
remark: "personalized"

checkpoint_path: './checkpoints'
exp_name: "FedRCL-P"
output_model_path: 'fedrcl_p_model.pt'
save_freq: 10
batch_size: 64
save_test: True

## Resume options
load_model_path: False
wandb_resume_id: False

###### wandb && logging ######
project: "FedRCL-Personalized"
log_dir: './checkpoints'

#################### Data Split ####################
split:
  mode: 'dirichlet'  # Options: 'iid', 'dirichlet', 'skew'
  alpha: 0.3  # Lower alpha = more non-IID
  class_per_client: 0  # Only for skew mode
  unbalanced: False
  overlap_ratio: 0.0
  create_client_dataset: False
  share_balanced_subset: true  # Share balanced data across clients
  samples_per_class: 50  # Number of samples per class in balanced subset
  samples_per_client: 20  # Number of samples to share with each client

#################### Optimizer ####################
optimizer:
  name: sgd
  momentum: 0.9
  wd: 1e-4

#################### Eval ####################
eval:
  freq: 5  # Evaluate every 5 rounds
  batch_size: 128

#################### Personalization Settings ####################
personalization:
  enable: true
  freeze_backbone: false  # Changed to false to allow backbone training in early rounds
  adaptive_layer_freezing: true

#################### Cyclical Learning Rate ####################
cyclical_lr:
  enable: true
  base_lr: 0.001
  max_lr: 0.1
  step_size: 10  # Number of rounds for half cycle

#################### Knowledge Distillation ####################
distillation:
  enable: true
  temperature: 3.0  # Increased from 2.0 for smoother probabilities
  weight: 0.7  # Increased from 0.5 for stronger knowledge transfer

#################### FedProx Regularization ####################
fedprox:
  enable: true
  mu: 0.005  # Reduced from 0.01 for less aggressive regularization

#################### EWC Regularization ####################
ewc:
  enable: true
  importance: 5000  # Importance weight for EWC regularization

analysis: True  # Enable analysis to track personalization benefits

#################### Default Configurations ####################
defaults:
  - _self_
  - trainer: personalized
  - client: personalized
  - evaler: base
  - dataset: cifar100
  - server: personalized
  - model: personalized_resnet18
